### ISSUE TITLE
Stuff in angled brackets does not display

### ISSUE THREAD

**Issue by zoffixznet** [perl6/perl6-examples#38] opened 2015-11-28 23:31 UTC
See http://examples.perl6.org/categories/interpreters/RPN.html
`my token Item { <Value> || <Op> };` on the site shows up as `my token  Item {  ||  };`

**Comment by bzipitidoo** [comment] 2015-11-28 23:43
Also wrong is the next line:
my token Expr { [<Item> <ws>]+ };

**Comment by bzipitidoo** [comment] 2015-11-29 02:18
Lot more missing text in angle brackets:  http://examples.perl6.org/categories/interpreters/lisp.html

**Comment by zoffixznet** [comment] 2015-11-29 02:22
I think all of those are caused by the same issue inside the [script that generates HTML](https://github.com/perl6/perl6-examples/blob/master/htmlify.pl), so there's no real need to hunt down every case.

**Comment by stmuk** [comment] 2015-11-29 22:53
This is now fixed.  The root causes were the behaviour of a conditional had changed such that the colour syntax wasn't being added.  This revealed that much of the site didn't escape html correctly in the absence of this.  There also were problems with the deployment system which is fragile and rakudo/panda themselves (I've stuck on old versions until curli is more stable).

**Closed by stmuk** 2015-11-29 22:53 UTC
